export const SET_IS_INITIALIZED = 'SET_IS_INITIALIZED';
export const SET_INDEXED_DB_SUPPORTED = 'SET_INDEXED_DB_SUPPORTED';
export const SET_SAVED_POSTS_COUNT = 'SET_SAVED_POSTS_COUNT';
export const SET_USER_SETTINGS = 'SET_USER_SETTINGS';
export const POST_MODAL_SHOW = 'SHOW_POST_MODAL';
export const POST_MODAL_HIDE = 'HIDE_POST_MODAL';
export const ERROR_MODAL_SHOW = 'ERROR_MODAL_SHOW';
export const ERROR_MODAL_HIDE = 'ERROR_MODAL_HIDE';
export const SET_SERVICE = 'SET_SERVICE';

export default {
  SET_IS_INITIALIZED,
  SET_INDEXED_DB_SUPPORTED,
  SET_SAVED_POSTS_COUNT,
  SET_USER_SETTINGS,
  POST_MODAL_SHOW,
  POST_MODAL_HIDE,
  ERROR_MODAL_SHOW,
  ERROR_MODAL_HIDE,
  SET_SERVICE,
};
